name: Refresh All Files on Push

on:
  push:
    branches:
      - v4

jobs:
  trigger-gas:
    runs-on: ubuntu-latest
    steps:
      - name: Call Google Apps Script Web App to Refresh
        run: curl "https://script.google.com/macros/s/AKfycbz8ELSxF45Qmhht5BYTDyIJ0KWc6Maydallcw7EdbmAW6m1pyEX0cCQWuJMcp5zvPo/exec?token=$GAS_REFRESH_TOKEN"
