name: Refresh All Files on Push

on:
  push:
    branches:
      - v4

jobs:
  trigger-gas:
    runs-on: ubuntu-latest
    steps:
      - name: Call Google Apps Script Web App to Refresh
        run: curl -L -d '' https://script.google.com/macros/s/AKfycbwk83i2jsWFhxKEgA2Ex2tsLIlfAqwjAXbqhuCaN15Py8ANboOwRBswHfOQGAbZm9w9/exec -H "Content-Type:application/json"
